#!/usr/bin/env node
// ai-news-morning-digest — runs daily at 00:25 UTC (09:25 JST), after the
// collector. Reads all Status=New rows from the Notion DB, asks Claude to
// write a short editorial intro, renders an HTML email grouped by importance,
// sends it via Gmail, and flips each item's Status to "Digested".
//
// Required env:
//   ANTHROPIC_API_KEY, NOTION_TOKEN, NOTION_AI_NEWS_DB_ID,
//   GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET, GMAIL_REFRESH_TOKEN, GMAIL_SENDER,
//   DIGEST_TO

import { env, todayJstISO, escapeHtml } from './lib/util.mjs';
import { queryDb, readPlain, setStatus } from './lib/notion.mjs';
import { generate } from './lib/claude.mjs';
import { sendMail } from './lib/gmail.mjs';

const ORDER = { High: 0, Medium: 1, Low: 2 };

function rowsFromPages(pages) {
  return pages.map(p => ({
    id: p.id,
    title: readPlain(p.properties?.Title),
    url: readPlain(p.properties?.URL),
    source: readPlain(p.properties?.Source),
    category: readPlain(p.properties?.Category) || 'Industry',
    importance: readPlain(p.properties?.Importance) || 'Medium',
    summary: readPlain(p.properties?.Summary),
  })).filter(r => r.title && r.url);
}

async function editorialIntro(rows) {
  const brief = rows.map(r => `- [${r.importance}/${r.category}] ${r.title} — ${r.summary}`).join('\n');
  const prompt = `You are writing the opening paragraph of a daily AI-industry email digest
delivered to a Japanese tech audience. Below are today's collected items.

Write 2–4 sentences in Japanese that (a) name the single most important
development of the day and why it matters, and (b) flag any cross-cutting
theme across the other items. No bullet points, no headings — prose only.
Do not introduce facts that are not in the list. If the list is empty,
output exactly: 本日は特筆すべき動きはありません。

Items:
${brief}`;
  return (await generate(prompt, { maxTokens: 600 })).trim();
}

function renderHtml(intro, rows, date) {
  rows.sort((a, b) => (ORDER[a.importance] ?? 9) - (ORDER[b.importance] ?? 9));
  const groups = new Map();
  for (const r of rows) {
    if (!groups.has(r.importance)) groups.set(r.importance, []);
    groups.get(r.importance).push(r);
  }

  const section = (label, items) => {
    if (!items || items.length === 0) return '';
    const rows = items.map(r => `
      <li style="margin:0 0 14px 0;">
        <div><a href="${escapeHtml(r.url)}" style="color:#0b5fff;text-decoration:none;font-weight:600;">${escapeHtml(r.title)}</a></div>
        <div style="color:#666;font-size:12px;margin-top:2px;">${escapeHtml(r.source)} · ${escapeHtml(r.category)}</div>
        <div style="margin-top:4px;font-size:14px;line-height:1.5;">${escapeHtml(r.summary)}</div>
      </li>`).join('');
    return `
      <h2 style="font-size:15px;border-bottom:1px solid #e5e5e5;padding-bottom:6px;margin:24px 0 12px;">${escapeHtml(label)}</h2>
      <ul style="list-style:none;padding:0;margin:0;">${rows}</ul>`;
  };

  return `<!doctype html>
<html><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:640px;margin:0 auto;padding:16px;color:#111;">
  <h1 style="font-size:18px;margin:0 0 8px;">AI News Digest — ${escapeHtml(date)}</h1>
  <p style="font-size:14px;line-height:1.6;color:#333;margin:0 0 8px;">${escapeHtml(intro)}</p>
  ${section('High importance', groups.get('High'))}
  ${section('Medium importance', groups.get('Medium'))}
  ${section('Low importance', groups.get('Low'))}
  <p style="font-size:11px;color:#999;margin-top:32px;">Generated by ai-news-morning-digest · ${escapeHtml(rows.length + '')} items</p>
</body></html>`;
}

async function main() {
  env('ANTHROPIC_API_KEY');
  env('NOTION_TOKEN');
  const dbId = env('NOTION_AI_NEWS_DB_ID');
  const to = env('DIGEST_TO');
  const date = todayJstISO();

  const pages = await queryDb(
    dbId,
    { property: 'Status', select: { equals: 'New' } },
    [{ property: 'Importance', direction: 'ascending' }],
  );
  const rows = rowsFromPages(pages);
  console.log(`[morning-digest] ${rows.length} new items`);

  if (rows.length === 0) {
    console.log('[morning-digest] nothing to send; exiting');
    return;
  }

  const intro = await editorialIntro(rows);
  const html = renderHtml(intro, rows, date);
  const subject = `AI News Digest — ${date} (${rows.length} items)`;

  await sendMail({ to, subject, html });
  console.log(`[morning-digest] sent to ${to}`);

  for (const p of pages) {
    try { await setStatus(p.id, 'Digested'); }
    catch (e) { console.error(`  status update failed for ${p.id}: ${e.message}`); }
  }
  console.log(`[morning-digest] marked ${pages.length} pages as Digested`);
}

await main();
